#general {
#  lock_cmd = pidof hyprlock || LIBGL_ALWAYS_SOFTWARE=1 hyprlock
#}


#listener {
#    timeout = 300                                 # 5min
#3    on-timeout = loginctl lock-session            # lock screen when timeout has passed
#}
